baseurl = "http://unixera.com/"
languageCode = "en-us"
title = "Me & Web"
copyright = "(c) 2013-2016 Frost Wong. All rights reserved."
theme = "beg"
# Pagination
canonifyurls = true
paginate = 10
paginatePath = "page"

[params]
    toc = true
    disqusShortname = "unixera"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[taxonomies]
    Tags = "tags"
    Topics = "topics"
    Categories = "categories"

[author]
    name = "Frost Wong"
    email = "frostwong@gmail.com"

[menu]
    [[menu.main]]
        name = "Home"
        pre = "<i class = 'fa fa-home fa-fw'></i>"
        weight = 0
        identifier = "home"
        url = "/"
    [[menu.main]]
        name = "Tags"
        pre = "<i class='fa fa-list fa-fw'></i>"
        weight = 1
        identifier = "tags"
        url = "/tags/"
    [[menu.main]]
        name = "Categories"
        pre = "<i class='fa fa-list fa-fw'></i>"
        weight = 1
        identifier = "categories"
        url = "/categories/"
    [[menu.main]]
        name = "About"
        pre = "<i class='fa fa-user fa-fw'></i>"
        weight = 2
        identifier = "about"
        url = "/about/"

