baseurl = "http://unixera.com/"
languageCode = "en-us"
title = "Me & Web"
copyright = "(c) 2013-2016 Frost Wong. All rights reserved."
theme = "hyde-y"
# Pagination
paginate = 5
paginatePath = "page"


[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "tags"
    topic = "topics"

[author]
    name = "Frost Wong"
    email = "frostwong@gmail.com"

[params]
    brand = "Frost Wong"
    topline = "Be a better WEB developer"
    footline = "Learn what you eager"
    sidebar = false
    highlight = "solarized_light"

    github = "lovelock"
    twitter = "frostwong"
    duoshuoShortname = "UnixAgain"
    linkedin = "青春-王-21466080"

[blackfriday]
    angleQuotes = true
    fractions = false
    hrefTargetBlank = true

