baseurl = "http://unixera.com/"
languageCode = "en-us"
title = "Me & Web"
copyright = "(c) 2013-2016 Frost Wong. All rights reserved."
theme = "blackburn"
# Pagination
canonifyurls = true
paginate = 10
paginatePath = "page"


[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "tags"
    topic = "topics"

[author]
    name = "Frost Wong"
    email = "frostwong@gmail.com"

[params]
    brand = "Frost Wong"
    topline = "Be a better WEB developer"
    footline = "Learn what you eager"
    sidebar = false
    highlightjs = "monokai"

[menu]
    [[menu.main]]
        name = "Home"
        pre = "<i class = 'fa fa-home fa-fw'></i>"
        weight = 0
        identifier = "home"
        url = "/"
    [[menu.main]]
        name = "Tags"
        pre = "<i class='fa fa-list fa-fw'></i>"
        weight = 1
        identifier = "tags"
        url = "/tags/"
    [[menu.main]]
        name = "About"
        pre = "<i class='fa fa-user fa-fw'></i>"
        weight = 2
        identifier = "about"
        url = "/about/"

[social]
    github = "lovelock"
    twitter = "frostwong"
    duoshuoShortname = "UnixAgain"
    linkedin = "青春-王-21466080"
    weibo = "2122681617"
